### ISSUE TITLE
3.0 Roadmap

### ISSUE THREAD

**Issue by VottusCode** [Snipcode/Snipcode#47]
- Complete Rework
  - [ ] Frontend - Editor
    - [ ] Support of multiple files
  - [ ] Frontend - Themes
    - [ ] Make the editor theme same as the rest of the site
    - [ ] Make multiple themes that user can choose
  - [ ] Frontend - Layout
    - [ ] Change the layout a bit to be more friendlye
  - [ ] Frontend - Link Shortener
    - [ ] Add the link shortener functionallity
  - [ ] Backend - Editor
    - [ ] Add support for multiple files
  - [ ] Backend - Themes
    - [ ] Integrate the multiple themes functionallity
  - [ ] Backend - Link Shortener
    - [ ] Add the link shortener functionallity
